### ISSUE TITLE
Having trouble working on mobile as root

### ISSUE THREAD

**Issue by Rick31d** [ARandomPerson7/Fixed-Jbro-ModLauncher#1]
Testei e está funcionando somente no emulador para computador, quando fui testar em meu celular não está funcionando não modifica a lib.
I tested it and it's working only on the computer emulator, when I went to test it on my cell phone it's not working it doesn't modify the lib.

**Comment by ARandomPerson7** [comment]
Its because you need to have a rooted device to make this work

**Comment by Rick31d** [comment]
![IMG_20210828_133620](https://user-images.githubusercontent.com/89699932/131224717-d61e3b86-164e-45a6-895a-142578e9616e.jpg)

Yes, my phone is rooted, but it doesn't change anything in the lib, I tested the same mod in the emulator and it works perfectly.

**Comment by Rick31d** [comment]
![Uploading IMG_20210828_134032.jpg…]()

**Comment by ARandomPerson7** [comment]
you probably used offsets for armv7 meaning you have to download an armv7
version of your game

**Comment by Rick31d** [comment]
Also check if the game has 32-bit architecture. I've given all read and write permissions by mt manager and it still doesn't work.

**Comment by Rick31d** [comment]
in my repository has a saved project that works perfectly everywhere, emulators, root, virtual. But I don't know how to add floatinng to it
